### ISSUE TITLE
New query pipeline needed to post-process results

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/susie-paper#3]
Dear Stephenslab,

Thank you for the fix before. 
I am on the numerical comparison part: https://stephenslab.github.io/susie-paper/manuscript_results/numerical_results.html
After using you latest version of susie_comparison.db and hard_case.db, I have the following error

`
Error in subset.default(susie_out, select = -c(lm_less.pve, fit_susie.prior_var,  :
  argument "subset" is missing, with no default
Calls: subset -> subset.default
Execution halted
ERROR: [cali_pip_2]: [(id=be844bb682ad6e57, index=0)]:
Failed to execute Rscript .sos/cali_pip_2_0_f0e695c5.R
exitcode=1, workdir=/net/wonderland/home/zaczhang/GIT/github/mvarbvs/dsc
`

**Comment by gaow** [comment]
@ZacZZZ at this point it seems you've got `susie_out` which should contain the result of the DSC benchmark using `dscrutils::dscquery()` function. However @pcarbo and I have made lots of revisions to that function since we posted the paper and those revisions were made without thinking too much into backwards compatibility. So contents of `susie_out` can be different and not compatible with what used to work with this pipeline. That's why it is hard to reproduce without using the docker image. I'm not sure what we can do at this point. 

I'm sorry about these frustrations. Not sure about your goal here but you can still check out `?dscrutils::dscquery` for the most up-to-date documentation for that function, and adapt the `dscquery()` call in my workflow under the old version of the function to the most current one. Notice with the current version you can load arbitrary quantities and use `tibble` to view them. For example you can ask for `method.pip` and have all PIP loaded to R workspace. This will save you from having to run `readRDS()` manually after the query as what I did in the workflow when we cannot handle complicated objects in `dscquery()` function back then. So very much likely most of my workflow script are obsolete if you use the new `dscquery()` smartly!

**Comment by ZacZZZ** [comment]
Hi @gaow 
Thanks for the help.
My goal is to set up the workflow of susie-R. And be able to modify the data generation or to modify the model fitting part on other datasets.
So I am both going through the https://stephenslab.github.io/dsc-wiki and following your set up instruction.

The error comes from running `sos run analysis/20180527_PIP_Workflow.ipynb cali_pip`

For the few suggested commands you gave can I know where one runs them?
I understand you the functions with () you can run them in R or SoS.

Besides, do you have suggestions on using a different data generation or testing other methods in DSC? I think I need to write some script in .DSC or to pass DSC the relevant scripts in .r or .py right?

**Comment by gaow** [comment]
> And be able to modify the data generation or to modify the model fitting part on other datasets. 

Then you don't need `sos run analysis/20180527_PIP_Workflow.ipynb cali_pip` and yes to extend my DSC benchmark you will have to write code in DSC. We have some basic tutorials on DSC website but there may still be a gap between being able to run those tutorials to being able to modify and extend the fine-mapping DSC. 

The commands I suggested is current version of `dscrutils::dscquery()` which is an R function you run it in R.

**Comment by ZacZZZ** [comment]
Can I know the running environment of `tibble` and `method.pip`?

**Comment by gaow** [comment]
@ZacZZZ I ended up updating `dscrutils` commands in those pipelines files, to using the latest DSC release. As a result you should no longer need to run from docker. You can reproduce my results with latest version of DSC.

To update it on your end, please follow every step in #2 . Notice you do have to download again meta data from step 1 and replace it again since I also just updated those meta-data.

At this point, I'm not expecting any issues from either running latest DSC installed on your computer, or from the docker image.
