### ISSUE TITLE
ValueError from docker image

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/susie-paper#6]
Hi Stephens Lab,

I got the dockerfile image setup on a virtual machine. 
When I run ` susie-docker dsc susie.dsc --target run_comparison -o toy_comparison`
it returns the following error
```
Traceback (most recent call last):
  File "/tmp/tmpf2roz728.py", line 6, in <module>
    DSC_28BD4D97 = __load_dsc__(['toy_comparison/liter_data/liter_data_1.rds'])
  File "/opt/miniconda3/lib/python3.7/site-packages/dsc/dsc_io.py", line 168, in load_dsc
    data = load_rds(infile)
  File "/opt/miniconda3/lib/python3.7/site-packages/dsc/dsc_io.py", line 98, in load_rds
    res = load_dict({}, rds, types)
  File "/opt/miniconda3/lib/python3.7/site-packages/dsc/dsc_io.py", line 89, in load_dict
    res[name] = load_dict(res[name], value, types)
  File "/opt/miniconda3/lib/python3.7/site-packages/dsc/dsc_io.py", line 91, in load_dict
    res[name] = load(value, types)
  File "/opt/miniconda3/lib/python3.7/site-packages/dsc/dsc_io.py", line 66, in load
    res = np.array(data, dtype = str)
ValueError: Buffer for this type not yet supported.
```

**Comment by ZacZZZ** [comment]
Hi @gaow, wondering it there is a way to fix this?

**Comment by gaow** [comment]
@ZacZZZ sorry for the delays. Unfortunately I cannot reproduce it on my end with the docker image I made last year. But looking into the Dockerfile I noticed some packages are not precisely versioned. That might be source of problems -- for docker images we should always version everything so it is my bad not to version some of them. Let me try later today to strictly version all packages on the docker image and get back to you.

**Comment by gaow** [comment]
@ZacZZZ from the error message, I guess the problem is `rpy2` and/or `reticulate` used in `dsc_io`. Both packages are under active development and might have backwards compatibility issues. I now have frozen both packages. If you pull the repo now and build the docker image and run the command you should not see a problem -- at least I just tried it on my computer it works. Notice that I have not changed versions for core software such as `R`, `susieR`, `finemap`, `CAVIAR` and `dap-g` so the benchmark should be consistent with what we used in SuSiE paper. Please let me know if there is still an issue.
